name: flutter_mates
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  http: '>=0.11.3+12'
  flutter:
    sdk: flutter
  uuid: ^2.0.0
  flutter_whatsnew: ^0.2.0+3
  shared_preferences: ^0.5.6+1
  local_auth: ^0.6.1
  cupertino_icons: ^0.1.2
  persist_theme: ^1.6.0
  json_annotation: ^2.0.0
  provider: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/profile_header_background.png
    - images/portfolio_1.jpeg
    - images/portfolio_2.jpeg
    - images/portfolio_3.jpeg
    - images/portfolio_4.jpeg
    - images/portfolio_5.jpeg
    - images/portfolio_6.jpeg